---
development:
  DB_FILENAME: 'infrastructure/database/dev.db'
  SECURE_SCHEME: 'HTTP'

test: 
  DB_FILENAME: 'infrastructure/database/test.db'
  SECURE_SCHEME: 'HTTP'

production:
  SECURE_SCHEME: 'HTTPS'

